validate:
    resource: "@ValidateBundle/Controller/"
    type:     annotation
    prefix:   /

acme_validate:
    resource: "@AcmeValidateBundle/Controller/"
    type:     annotation
    prefix:   /

